# application: bkk-1
# version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "30s"

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: backend.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
  - remote_api: on
